front:
  build: ./nginx
  container_name: "nginx"
  ports:
    - 8888:80
  environment:
    - KVSTORE=192.168.99.132:8500
api:
  build: ./python
  environment:
    - HOST=mongo
db:
  image: mongo
  container_name: "mongo"
