front:
  build: ./nginx
  container_name: "nginx"
  ports:
    - 8888:80
  environment:
    - "constraint:node==swarm-master"
api:
  build: ./python
  environment:
    - "constraint:node==swarm-slave2"
    - HOST=mongo
db:
  image: mongo
  container_name: "mongo"
  environment:
    - "constraint:node==swarm-slave3"
