front:
  build: ./nginx
  container_name: "nginx"
  ports:
    - 8888:80
  environment:
    - "contraint:environment==frontend"
api:
  build: ./python
  container_name: "python"
  environment:
    - HOST=mongodb://mongo:27017/dockerconeu
    - "contraint:environment==middleend"
db:
  image: mongo
  container_name: "mongo"
  environment:
    - "contraint:environment==backend"
